//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocCommander.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DocCommanderEntities : DbContext
    {
        public DocCommanderEntities()
            : base("name=DocCommanderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccessLevel> AccessLevels { get; set; }
        public DbSet<Account> Accounts { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
        public DbSet<SysListItem> SysListItems { get; set; }
        public DbSet<AppEvent> AppEvents { get; set; }
        public DbSet<Num> Nums { get; set; }
        public DbSet<SysList> SysLists { get; set; }
        public DbSet<NumConfig> NumConfigs { get; set; }
    }
}
