//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocCommander.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumConfig
    {
        public NumConfig()
        {
            this.Nums = new HashSet<Num>();
        }
    
        public int NumConfigId { get; set; }
        public string Name { get; set; }
        public bool IsHierarchy { get; set; }
        public string Part1ListName { get; set; }
        public string Part2ListName { get; set; }
        public string Part3ListName { get; set; }
        public string Part4ListName { get; set; }
        public string Part5ListName { get; set; }
        public string Part1String { get; set; }
        public string Part2String { get; set; }
        public string Part3String { get; set; }
        public string Part4String { get; set; }
        public string Part5String { get; set; }
    
        public virtual ICollection<Num> Nums { get; set; }
    }
}
