//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocCommander.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumConfig
    {
        public NumConfig()
        {
            this.Nums = new HashSet<Num>();
        }
    
        public int NumConfigId { get; set; }
        public int Part1List { get; set; }
        public Nullable<int> Part2List { get; set; }
        public Nullable<int> Part3List { get; set; }
        public Nullable<int> Part4List { get; set; }
        public Nullable<int> Part5List { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Num> Nums { get; set; }
    }
}
