//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocCommander.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysListItem
    {
        public int SysListItemId { get; set; }
        public int SysListId { get; set; }
        public string Value { get; set; }
        public string ShortCode { get; set; }
    
        public virtual SysList SysList { get; set; }
    }
}
