//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocCommander.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysList
    {
        public SysList()
        {
            this.SysListItems = new HashSet<SysListItem>();
        }
    
        public int SysListId { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<SysListItem> SysListItems { get; set; }
    }
}
